# This is a basic workflow to help you get started with Actions

name: create_summary_csv

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main branch
  # also runs nightly as a cron job
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_summary_csv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        
      - name: Run the Python Summarization Script that will create the new summary.csv file.
        working-directory: ./scripts
        run: |
          date > summary_csv_script_log.txt
          python3 create_summary_csv.py -i ../problem_instances -o ../summary.csv >> summary_csv_script_log.txt 2>&1
        
      - name: commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add -A
          git commit -m "Automatic Update of summary.csv"
          git push
          # git push origin 
          
